/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    useri: UseriAuthOperations;
  };
  blocks: {};
  collections: {
    articole: Articole;
    surse: Surse;
    categorii: Categorii;
    useri: Useri;
    comentarii: Comentarii;
    tooluri: Tooluri;
    roadmaps: Roadmap;
    cursuri: Cursuri;
    'callouri-ue': CallouriUe;
    newsletter: Newsletter;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articole: ArticoleSelect<false> | ArticoleSelect<true>;
    surse: SurseSelect<false> | SurseSelect<true>;
    categorii: CategoriiSelect<false> | CategoriiSelect<true>;
    useri: UseriSelect<false> | UseriSelect<true>;
    comentarii: ComentariiSelect<false> | ComentariiSelect<true>;
    tooluri: TooluriSelect<false> | TooluriSelect<true>;
    roadmaps: RoadmapsSelect<false> | RoadmapsSelect<true>;
    cursuri: CursuriSelect<false> | CursuriSelect<true>;
    'callouri-ue': CallouriUeSelect<false> | CallouriUeSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ro' | 'en') | ('ro' | 'en')[];
  globals: {};
  globalsSelect: {};
  locale: 'ro' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Useri;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UseriAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articole".
 */
export interface Articole {
  id: number;
  titlu: string;
  /**
   * URL-friendly. Se folosește în /ro/articol/{slug} sau /en/article/{slug}
   */
  slug: string;
  limba: 'ro' | 'en';
  /**
   * Articolul echivalent în cealaltă limbă (pentru butonul RO/EN și hreflang SEO).
   */
  versiuneAlternativa?: (number | null) | Articole;
  continutHashTradus?: string | null;
  /**
   * ⚠️ Conținutul a fost modificat după ultima traducere. Retradu manual dacă e nevoie.
   */
  necesitaRetraducere?: boolean | null;
  /**
   * Pilonul de care aparține (cei 5 piloni de conținut).
   */
  pilon: number | Categorii;
  /**
   * Subcategorie — relevant mai ales pentru pilonul Sănătate.
   */
  subcategorie?: ('diagnostic' | 'medicamente' | 'asistenta-clinica' | 'reglementare' | 'pacienti') | null;
  /**
   * Subcategorie — relevant mai ales pentru pilonul Educație.
   */
  subcategorieEducatie?: ('invatare-ai' | 'institutii' | 'instrumente-edu' | 'cercetare' | 'cariere') | null;
  /**
   * Eticheta de tip — vizibilă cititorului (regula 5 din compliance).
   */
  tip: 'stire-auto' | 'analiza' | 'frontiera' | 'ghid';
  /**
   * Rezumat scurt pentru liste și meta description.
   */
  excerpt?: string | null;
  continut: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  imaginePrincipala?: (number | null) | Media;
  /**
   * Imagini pentru corpul articolului. Fiecare cu descriere și credit/sursă.
   */
  galerie?:
    | {
        imagine: number | Media;
        /**
         * Descriere afișată sub imagine.
         */
        caption?: string | null;
        /**
         * Credit/sursă imagine (pentru drepturi de autor).
         */
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Titlu opțional pentru video.
   */
  videoTitlu?: string | null;
  /**
   * Link YouTube sau Vimeo (ex: https://www.youtube.com/watch?v=...).
   */
  videoUrl?: string | null;
  /**
   * Sursele citate. Minimum 2 pentru conformitate.
   */
  surse?: (number | Surse)[] | null;
  /**
   * Numele sursei originale (ex: Tech.eu, TechCrunch).
   */
  sursaNume?: string | null;
  /**
   * Link-ul concret al articolului-sursă original.
   */
  sursaLink?: string | null;
  /**
   * Compania/laboratorul care dezvoltă tehnologia (ex: Aidoc).
   */
  producator?: string | null;
  /**
   * Link oficial al producătorului (ex: https://www.aidoc.com).
   */
  linkProducator?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'review' | 'published' | 'blocked';
  /**
   * Știre excepțională / breaking news.
   */
  esteBreaking?: boolean | null;
  publishedAt?: string | null;
  /**
   * Hash de deduplicare tematică.
   */
  clusterHash?: string | null;
  /**
   * Unghiul editorial (general, cronologie, analiza...).
   */
  unghi?: string | null;
  generatAutomat?: boolean | null;
  corectatCompliance?: boolean | null;
  /**
   * Surse independente care confirmă.
   */
  numarConfirmari?: number | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorii".
 */
export interface Categorii {
  id: number;
  nume: string;
  slug: string;
  pilon: 'stiri' | 'sanatate' | 'educatie' | 'tools' | 'afaceri';
  descriere?: string | null;
  /**
   * Bifat pentru Pilonul 2 — declanșează disclaimerul medical.
   */
  necesitaDisclaimer?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Text alternativ — accesibilitate și SEO.
   */
  alt?: string | null;
  /**
   * Hash pentru deduplicare (blacklist imagini repetate).
   */
  hashMD5?: string | null;
  sursaImagine?: ('pexels' | 'pixabay' | 'unsplash' | 'proprie') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surse".
 */
export interface Surse {
  id: number;
  nume: string;
  /**
   * URL-ul de bază al sursei.
   */
  url: string;
  nivelIncredere: 'primar' | 'secundar' | 'speculativ';
  tipCitarePermis: 'citat-scurt' | 'parafrazare' | 'frontiera';
  /**
   * Dacă Auto-Publisher poate genera articole din această sursă. Speculativ = de obicei false.
   */
  permiteAutoGenerare?: boolean | null;
  /**
   * Pilonii pentru care e relevantă această sursă.
   */
  pilon?: (number | Categorii)[] | null;
  /**
   * URL feed RSS, dacă există (pentru Auto-Publisher).
   */
  feedRSS?: string | null;
  regiune?: ('global' | 'europa' | 'romania') | null;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useri".
 */
export interface Useri {
  id: number;
  nume?: string | null;
  rol: 'cititor' | 'contributor' | 'editor' | 'admin';
  nivelAbonament?: ('gratuit' | 'premium' | 'complet') | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  abonamentExpira?: string | null;
  limbaPreferata?: ('ro' | 'en') | null;
  abonatNewsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'useri';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comentarii".
 */
export interface Comentarii {
  id: number;
  continut: string;
  autor: number | Useri;
  articol: number | Articole;
  /**
   * Moderare din ziua 1 — comentariile apar public doar după aprobare.
   */
  status: 'asteptare' | 'aprobat' | 'respins';
  /**
   * Pentru thread-uri (răspuns la alt comentariu).
   */
  raspunsLa?: (number | null) | Comentarii;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tooluri".
 */
export interface Tooluri {
  id: number;
  nume: string;
  slug: string;
  /**
   * Descriere scurtă pentru card (1-2 fraze). Bilingv prin localizare.
   */
  descriere?: string | null;
  website: string;
  /**
   * Link de afiliere, dacă există. Se declară afilierea în pagină.
   */
  linkAfiliat?: string | null;
  logo?: (number | null) | Media;
  categorieTool?: ('text' | 'imagine' | 'video' | 'cod' | 'audio' | 'productivitate' | 'cercetare')[] | null;
  /**
   * Scor editorial 0-10.
   */
  scor?: number | null;
  pret?: ('gratuit' | 'freemium' | 'platit') | null;
  recenzie?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Realizări remarcabile probate practic.
   */
  studiuDeCaz?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ultima verificare a statusului — directorul trebuie ținut la zi.
   */
  verificatLa?: string | null;
  activ?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps".
 */
export interface Roadmap {
  id: number;
  titlu: string;
  slug: string;
  descriere?: string | null;
  nivel?: ('incepator' | 'intermediar' | 'avansat') | null;
  pasi?:
    | {
        titlu: string;
        descriere?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        resurse?:
          | {
              titlu?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursuri".
 */
export interface Cursuri {
  id: number;
  titlu: string;
  slug: string;
  descriere?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imagine?: (number | null) | Media;
  /**
   * Curs gratuit sau necesită abonament complet.
   */
  gratuit?: boolean | null;
  /**
   * Stripe Price ID, dacă e vândut individual.
   */
  pretStripe?: string | null;
  lectii?:
    | {
        titlu: string;
        continut?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        videoURL?: string | null;
        durataMinute?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callouri-ue".
 */
export interface CallouriUe {
  id: number;
  titlu: string;
  program?: ('eic-accelerator' | 'eic-pre' | 'genai4eu' | 'horizon' | 'digital-europe' | 'altele') | null;
  descriere?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ex: "2,5M€ grant + 15M€ equity".
   */
  finantareMax?: string | null;
  deadline?: string | null;
  /**
   * Evidențiat — multe programe au România în grupul widening.
   */
  eligibilRomania?: boolean | null;
  pilonRelevant?: (number | Categorii)[] | null;
  linkOficial: string;
  activ?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email: string;
  limba?: ('ro' | 'en') | null;
  segment?: ('general' | 'profesionisti' | 'studenti' | 'callouri')[] | null;
  /**
   * Double opt-in confirmat.
   */
  confirmat?: boolean | null;
  userAsociat?: (number | null) | Useri;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articole';
        value: number | Articole;
      } | null)
    | ({
        relationTo: 'surse';
        value: number | Surse;
      } | null)
    | ({
        relationTo: 'categorii';
        value: number | Categorii;
      } | null)
    | ({
        relationTo: 'useri';
        value: number | Useri;
      } | null)
    | ({
        relationTo: 'comentarii';
        value: number | Comentarii;
      } | null)
    | ({
        relationTo: 'tooluri';
        value: number | Tooluri;
      } | null)
    | ({
        relationTo: 'roadmaps';
        value: number | Roadmap;
      } | null)
    | ({
        relationTo: 'cursuri';
        value: number | Cursuri;
      } | null)
    | ({
        relationTo: 'callouri-ue';
        value: number | CallouriUe;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'useri';
    value: number | Useri;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'useri';
    value: number | Useri;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articole_select".
 */
export interface ArticoleSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  limba?: T;
  versiuneAlternativa?: T;
  continutHashTradus?: T;
  necesitaRetraducere?: T;
  pilon?: T;
  subcategorie?: T;
  subcategorieEducatie?: T;
  tip?: T;
  excerpt?: T;
  continut?: T;
  imaginePrincipala?: T;
  galerie?:
    | T
    | {
        imagine?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  videoTitlu?: T;
  videoUrl?: T;
  surse?: T;
  sursaNume?: T;
  sursaLink?: T;
  producator?: T;
  linkProducator?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  esteBreaking?: T;
  publishedAt?: T;
  clusterHash?: T;
  unghi?: T;
  generatAutomat?: T;
  corectatCompliance?: T;
  numarConfirmari?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surse_select".
 */
export interface SurseSelect<T extends boolean = true> {
  nume?: T;
  url?: T;
  nivelIncredere?: T;
  tipCitarePermis?: T;
  permiteAutoGenerare?: T;
  pilon?: T;
  feedRSS?: T;
  regiune?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorii_select".
 */
export interface CategoriiSelect<T extends boolean = true> {
  nume?: T;
  slug?: T;
  pilon?: T;
  descriere?: T;
  necesitaDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useri_select".
 */
export interface UseriSelect<T extends boolean = true> {
  nume?: T;
  rol?: T;
  nivelAbonament?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  abonamentExpira?: T;
  limbaPreferata?: T;
  abonatNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comentarii_select".
 */
export interface ComentariiSelect<T extends boolean = true> {
  continut?: T;
  autor?: T;
  articol?: T;
  status?: T;
  raspunsLa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tooluri_select".
 */
export interface TooluriSelect<T extends boolean = true> {
  nume?: T;
  slug?: T;
  descriere?: T;
  website?: T;
  linkAfiliat?: T;
  logo?: T;
  categorieTool?: T;
  scor?: T;
  pret?: T;
  recenzie?: T;
  studiuDeCaz?: T;
  verificatLa?: T;
  activ?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps_select".
 */
export interface RoadmapsSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  descriere?: T;
  nivel?: T;
  pasi?:
    | T
    | {
        titlu?: T;
        descriere?: T;
        resurse?:
          | T
          | {
              titlu?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursuri_select".
 */
export interface CursuriSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  descriere?: T;
  imagine?: T;
  gratuit?: T;
  pretStripe?: T;
  lectii?:
    | T
    | {
        titlu?: T;
        continut?: T;
        videoURL?: T;
        durataMinute?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callouri-ue_select".
 */
export interface CallouriUeSelect<T extends boolean = true> {
  titlu?: T;
  program?: T;
  descriere?: T;
  finantareMax?: T;
  deadline?: T;
  eligibilRomania?: T;
  pilonRelevant?: T;
  linkOficial?: T;
  activ?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  limba?: T;
  segment?: T;
  confirmat?: T;
  userAsociat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  hashMD5?: T;
  sursaImagine?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}