/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    useri: UseriAuthOperations;
  };
  blocks: {};
  collections: {
    articole: Articole;
    autori: Autori;
    surse: Surse;
    categorii: Categorii;
    useri: Useri;
    comentarii: Comentarii;
    tooluri: Tooluri;
    roadmaps: Roadmap;
    cursuri: Cursuri;
    'callouri-ue': CallouriUe;
    newsletter: Newsletter;
    media: Media;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articole: ArticoleSelect<false> | ArticoleSelect<true>;
    autori: AutoriSelect<false> | AutoriSelect<true>;
    surse: SurseSelect<false> | SurseSelect<true>;
    categorii: CategoriiSelect<false> | CategoriiSelect<true>;
    useri: UseriSelect<false> | UseriSelect<true>;
    comentarii: ComentariiSelect<false> | ComentariiSelect<true>;
    tooluri: TooluriSelect<false> | TooluriSelect<true>;
    roadmaps: RoadmapsSelect<false> | RoadmapsSelect<true>;
    cursuri: CursuriSelect<false> | CursuriSelect<true>;
    'callouri-ue': CallouriUeSelect<false> | CallouriUeSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ro' | 'en') | ('ro' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'ro' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Useri;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UseriAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articole".
 */
export interface Articole {
  id: number;
  titlu: string;
  /**
   * URL-friendly. Se folosește în /ro/articol/{slug} sau /en/article/{slug}
   */
  slug: string;
  limba: 'ro' | 'en';
  /**
   * Articolul echivalent în cealaltă limbă (pentru butonul RO/EN și hreflang SEO).
   */
  versiuneAlternativa?: (number | null) | Articole;
  continutHashTradus?: string | null;
  /**
   * ⚠️ Conținutul a fost modificat după ultima traducere. Retradu manual dacă e nevoie.
   */
  necesitaRetraducere?: boolean | null;
  /**
   * Pilonul de care aparține (cei 5 piloni de conținut).
   */
  pilon: number | Categorii;
  /**
   * Subcategorie — relevant mai ales pentru pilonul Sănătate.
   */
  subcategorie?: ('diagnostic' | 'medicamente' | 'asistenta-clinica' | 'reglementare' | 'pacienti') | null;
  /**
   * Subcategorie — relevant mai ales pentru pilonul Educație.
   */
  subcategorieEducatie?: ('invatare-ai' | 'institutii' | 'instrumente-edu' | 'cercetare' | 'cariere') | null;
  /**
   * Eticheta de tip — vizibilă cititorului (regula 5 din compliance).
   */
  tip: 'stire-auto' | 'analiza' | 'frontiera' | 'ghid';
  /**
   * Rezumat scurt pentru liste și meta description.
   */
  excerpt?: string | null;
  continut: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  imaginePrincipala?: (number | null) | Media;
  /**
   * Imagini pentru corpul articolului. Fiecare cu descriere și credit/sursă.
   */
  galerie?:
    | {
        imagine: number | Media;
        /**
         * Descriere afișată sub imagine.
         */
        caption?: string | null;
        /**
         * Credit/sursă imagine (pentru drepturi de autor).
         */
        credit?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Titlu opțional pentru video.
   */
  videoTitlu?: string | null;
  /**
   * Link YouTube sau Vimeo (ex: https://www.youtube.com/watch?v=...).
   */
  videoUrl?: string | null;
  /**
   * Sursele citate. Minimum 2 pentru conformitate.
   */
  surse?: (number | Surse)[] | null;
  /**
   * Numele sursei originale (ex: Tech.eu, TechCrunch).
   */
  sursaNume?: string | null;
  /**
   * Link-ul concret al articolului-sursă original.
   */
  sursaLink?: string | null;
  /**
   * Compania/laboratorul care dezvoltă tehnologia (ex: Aidoc).
   */
  producator?: string | null;
  /**
   * Link oficial al producătorului (ex: https://www.aidoc.com).
   */
  linkProducator?: string | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Autorul principal al articolului. Relația nu înlocuiește rolurile generale din profilul autorului.
   */
  autorPrincipal?: (number | null) | Autori;
  /**
   * Coautorii articolului, în ordinea în care trebuie considerați editorial.
   */
  coautori?: (number | Autori)[] | null;
  /**
   * Persoana care a realizat verificarea editorială a articolului.
   */
  verificatorEditorial?: (number | null) | Autori;
  /**
   * Verificator medical, utilizat numai când articolul necesită o astfel de validare.
   */
  verificatorMedical?: (number | null) | Autori;
  /**
   * Experți sau evaluatori care au contribuit editorial la articol.
   */
  contributoriExperti?: (number | Autori)[] | null;
  editorialStatus: 'draft' | 'review' | 'approved' | 'blocked';
  /**
   * Știre excepțională / breaking news.
   */
  esteBreaking?: boolean | null;
  publishedAt?: string | null;
  /**
   * Completează doar când articolul a primit o actualizare editorială semnificativă pentru cititor.
   */
  significantUpdatedAt?: string | null;
  /**
   * Hash de deduplicare tematică.
   */
  clusterHash?: string | null;
  /**
   * Unghiul editorial (general, cronologie, analiza...).
   */
  unghi?: string | null;
  generatAutomat?: boolean | null;
  corectatCompliance?: boolean | null;
  /**
   * Surse independente care confirmă.
   */
  numarConfirmari?: number | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorii".
 */
export interface Categorii {
  id: number;
  nume: string;
  slug: string;
  pilon: 'stiri' | 'sanatate' | 'educatie' | 'tools' | 'afaceri';
  descriere?: string | null;
  /**
   * Bifat pentru Pilonul 2 — declanșează disclaimerul medical.
   */
  necesitaDisclaimer?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Text alternativ — accesibilitate și SEO.
   */
  alt?: string | null;
  /**
   * Hash pentru deduplicare (blacklist imagini repetate).
   */
  hashMD5?: string | null;
  sursaImagine?: ('pexels' | 'pixabay' | 'unsplash' | 'proprie' | 'alta') | null;
  /**
   * Bifează doar dacă dreptul 844-ai.ro de a publica imaginea a fost verificat.
   */
  dreptUtilizareConfirmat?: boolean | null;
  /**
   * Opțional. Credit / atribuire pentru imagine, când sursa sau licența o cere.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surse".
 */
export interface Surse {
  id: number;
  nume: string;
  /**
   * URL-ul de bază al sursei.
   */
  url: string;
  nivelIncredere: 'primar' | 'secundar' | 'speculativ';
  tipCitarePermis: 'citat-scurt' | 'parafrazare' | 'frontiera';
  /**
   * Dacă Auto-Publisher poate genera articole din această sursă. Speculativ = de obicei false.
   */
  permiteAutoGenerare?: boolean | null;
  /**
   * Pilonii pentru care e relevantă această sursă.
   */
  pilon?: (number | Categorii)[] | null;
  /**
   * URL feed RSS, dacă există (pentru Auto-Publisher).
   */
  feedRSS?: string | null;
  regiune?: ('global' | 'europa' | 'romania') | null;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autori".
 */
export interface Autori {
  id: number;
  profileType: 'person' | 'editorialSystem';
  fullName: string;
  /**
   * Identificator stabil pentru ruta publică. După creare nu se regenerează automat din nume.
   */
  slug: string;
  publicTitle?: string | null;
  primaryAffiliation?: string | null;
  profileImage?: (number | null) | Media;
  /**
   * Recomandată pentru publicare și utilizată în carduri și antetul profilului.
   */
  shortBio?: string | null;
  /**
   * Editor controlat: paragrafe, H2/H3, formatare de bază, linkuri, liste și citate.
   */
  biography?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  platformRoleDescription?: string | null;
  /**
   * Numai o localizare generală, precum orașul sau țara. Nu introduceți adrese private.
   */
  publicLocation?: string | null;
  displayOrder?: number | null;
  /**
   * Cel puțin un rol va deveni obligatoriu la publicarea profilului.
   */
  editorialRoles?:
    | (
        | 'author'
        | 'coauthor'
        | 'editorialReviewer'
        | 'medicalReviewer'
        | 'technicalReviewer'
        | 'toolEvaluator'
        | 'courseAuthor'
        | 'instructor'
        | 'contentCurator'
        | 'externalExpert'
      )[]
    | null;
  expertiseAreas?:
    | {
        name: string;
        description?: string | null;
        /**
         * Indicator intern. Nu va fi inclus în datele publice.
         */
        verified?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  specialties?:
    | {
        label: string;
        description?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  contributionTypes?:
    | (
        | 'articles'
        | 'flashAI'
        | 'courses'
        | 'roadmaps'
        | 'toolReviews'
        | 'euCalls'
        | 'medicalContent'
        | 'editorialReview'
      )[]
    | null;
  /**
   * Indicator controlat intern. La publicare necesită o calificare verificată și neexpirată.
   */
  isMedicalReviewer?: boolean | null;
  /**
   * Descrie limitele domeniului în care persoana poate verifica informații medicale.
   */
  medicalReviewScope?: string | null;
  credentials?:
    | {
        credentialType:
          | 'academicDegree'
          | 'professionalTitle'
          | 'medicalLicense'
          | 'certification'
          | 'training'
          | 'membership'
          | 'other';
        title: string;
        institution?: string | null;
        country?: string | null;
        yearObtained?: number | null;
        yearExpires?: number | null;
        identifier?: string | null;
        verificationUrl?: string | null;
        /**
         * Calificarea poate fi expusă public numai dacă este și verificată.
         */
        publiclyVisible?: boolean | null;
        verified?: boolean | null;
        verifiedAt?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  professionalIdentifiers?:
    | {
        type?:
          | ('orcid' | 'researcherId' | 'professionalRegistry' | 'medicalRegistry' | 'institutionalProfile' | 'other')
          | null;
        value: string;
        publiclyVisible?: boolean | null;
        verificationUrl?: string | null;
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  verificationStatus: 'pending' | 'partiallyVerified' | 'verified' | 'expired' | 'rejected';
  verifiedAt?: string | null;
  verifiedBy?: (number | null) | Useri;
  verificationSource?: string | null;
  nextVerificationDue?: string | null;
  verificationNotes?: string | null;
  documentsReviewed?: boolean | null;
  /**
   * Se completează numai cu acordul explicit al persoanei.
   */
  publicEmail?: string | null;
  website?: string | null;
  institutionalProfile?: string | null;
  orcidUrl?: string | null;
  socialLinks?:
    | {
        platform:
          | 'linkedin'
          | 'github'
          | 'youtube'
          | 'x'
          | 'facebook'
          | 'instagram'
          | 'researchGate'
          | 'googleScholar'
          | 'other';
        label?: string | null;
        url: string;
        enabled?: boolean | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  conflictOfInterestStatement?: string | null;
  affiliationsAndSponsorships?:
    | {
        organization: string;
        relationshipType:
          | 'employment'
          | 'consulting'
          | 'researchFunding'
          | 'sponsorship'
          | 'partnership'
          | 'advisoryRole'
          | 'ownership'
          | 'speakerFee'
          | 'other';
        description?: string | null;
        startDate?: string | null;
        endDate?: string | null;
        currentlyActive?: boolean | null;
        /**
         * Se păstrează activ numai pentru relațiile relevante pentru transparența editorială.
         */
        publiclyVisible?: boolean | null;
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  aiUseDisclosure?: string | null;
  /**
   * Va fi obligatoriu logic înainte de trecerea profilului în starea publicată.
   */
  publicationConsent?: boolean | null;
  consentConfirmedAt?: string | null;
  consentConfirmedBy?: (number | null) | Useri;
  consentScope?: string | null;
  profileImageConsent?: boolean | null;
  publicContactConsent?: boolean | null;
  consentWithdrawnAt?: string | null;
  consentNotes?: string | null;
  /**
   * Numai administratorul poate modifica starea profilului în prima implementare.
   */
  status: 'draft' | 'pendingVerification' | 'verified' | 'published' | 'inactive' | 'archived';
  /**
   * Este completată automat la prima trecere în starea Publicat.
   */
  publishedAt?: string | null;
  lastReviewedAt?: string | null;
  nextReviewDue?: string | null;
  inactiveAt?: string | null;
  archivedAt?: string | null;
  /**
   * Câmp intern pentru trasabilitatea verificării editoriale.
   */
  reviewedBy?: (number | null) | Useri;
  /**
   * Obligatoriu logic atunci când profilul este în starea Arhivat.
   */
  archivalReason?: string | null;
  /**
   * Relație internă opțională. Asocierea nu acordă drepturi de acces și nu creează automat un profil public.
   */
  linkedUser?: (number | null) | Useri;
  /**
   * Opțional. Frontendul va utiliza fallbackul aprobat când lipsește.
   */
  metaTitle?: string | null;
  /**
   * Opțional. Frontendul va utiliza biografia scurtă ca fallback.
   */
  metaDescription?: string | null;
  /**
   * Opțional. Fallback: fotografia autorului, apoi imaginea globală din SiteSettings.
   */
  socialImage?: (number | null) | Media;
  /**
   * Frontendul va forța noindex pentru orice profil care nu este în starea Published.
   */
  robots: 'indexFollow' | 'noindexFollow' | 'noindexNofollow';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useri".
 */
export interface Useri {
  id: number;
  nume?: string | null;
  rol: 'cititor' | 'contributor' | 'editor' | 'admin';
  nivelAbonament?: ('gratuit' | 'premium' | 'complet') | null;
  stripeCustomerId?: string | null;
  stripeSubscriptionId?: string | null;
  abonamentExpira?: string | null;
  limbaPreferata?: ('ro' | 'en') | null;
  abonatNewsletter?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'useri';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comentarii".
 */
export interface Comentarii {
  id: number;
  continut: string;
  autor: number | Useri;
  articol: number | Articole;
  /**
   * Moderare din ziua 1 — comentariile apar public doar după aprobare.
   */
  status: 'asteptare' | 'aprobat' | 'respins';
  /**
   * Pentru thread-uri (răspuns la alt comentariu).
   */
  raspunsLa?: (number | null) | Comentarii;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tooluri".
 */
export interface Tooluri {
  id: number;
  nume: string;
  slug: string;
  /**
   * Descriere scurtă pentru card (1-2 fraze). Bilingv prin localizare.
   */
  descriere?: string | null;
  website: string;
  /**
   * Link de afiliere, dacă există. Se declară afilierea în pagină.
   */
  linkAfiliat?: string | null;
  logo?: (number | null) | Media;
  categorieTool?: ('text' | 'imagine' | 'video' | 'cod' | 'audio' | 'productivitate' | 'cercetare')[] | null;
  /**
   * Scor editorial 0-10.
   */
  scor?: number | null;
  pret?: ('gratuit' | 'freemium' | 'platit') | null;
  recenzie?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Realizări remarcabile probate practic.
   */
  studiuDeCaz?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ultima verificare a statusului — directorul trebuie ținut la zi.
   */
  verificatLa?: string | null;
  activ?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps".
 */
export interface Roadmap {
  id: number;
  titlu: string;
  slug: string;
  descriere?: string | null;
  nivel?: ('incepator' | 'intermediar' | 'avansat') | null;
  pasi?:
    | {
        titlu: string;
        descriere?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        resurse?:
          | {
              titlu?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursuri".
 */
export interface Cursuri {
  id: number;
  titlu: string;
  slug: string;
  descriere?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  imagine?: (number | null) | Media;
  /**
   * Curs gratuit sau necesită abonament complet.
   */
  gratuit?: boolean | null;
  /**
   * Stripe Price ID, dacă e vândut individual.
   */
  pretStripe?: string | null;
  lectii?:
    | {
        titlu: string;
        continut?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        videoURL?: string | null;
        durataMinute?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callouri-ue".
 */
export interface CallouriUe {
  id: number;
  titlu: string;
  program?: ('eic-accelerator' | 'eic-pre' | 'genai4eu' | 'horizon' | 'digital-europe' | 'altele') | null;
  descriere?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Ex: "2,5M€ grant + 15M€ equity".
   */
  finantareMax?: string | null;
  deadline?: string | null;
  /**
   * Evidențiat — multe programe au România în grupul widening.
   */
  eligibilRomania?: boolean | null;
  pilonRelevant?: (number | Categorii)[] | null;
  linkOficial: string;
  activ?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email: string;
  limba?: ('ro' | 'en') | null;
  segment?: ('general' | 'profesionisti' | 'studenti' | 'callouri')[] | null;
  /**
   * Double opt-in confirmat.
   */
  confirmat?: boolean | null;
  /**
   * Metadată internă pentru cooldown-ul emailurilor de confirmare.
   */
  confirmationLastSentAt?: string | null;
  userAsociat?: (number | null) | Useri;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'articole';
    value: number | Articole;
  };
  excerpt?: string | null;
  keywords?: string | null;
  url?: string | null;
  language?: ('ro' | 'en') | null;
  editorialStatus?: ('draft' | 'review' | 'approved' | 'blocked') | null;
  articleType?: ('stire-auto' | 'analiza' | 'frontiera' | 'ghid') | null;
  publishedAt?: string | null;
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'articole';
        value: number | Articole;
      } | null)
    | ({
        relationTo: 'autori';
        value: number | Autori;
      } | null)
    | ({
        relationTo: 'surse';
        value: number | Surse;
      } | null)
    | ({
        relationTo: 'categorii';
        value: number | Categorii;
      } | null)
    | ({
        relationTo: 'useri';
        value: number | Useri;
      } | null)
    | ({
        relationTo: 'comentarii';
        value: number | Comentarii;
      } | null)
    | ({
        relationTo: 'tooluri';
        value: number | Tooluri;
      } | null)
    | ({
        relationTo: 'roadmaps';
        value: number | Roadmap;
      } | null)
    | ({
        relationTo: 'cursuri';
        value: number | Cursuri;
      } | null)
    | ({
        relationTo: 'callouri-ue';
        value: number | CallouriUe;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'useri';
    value: number | Useri;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'useri';
    value: number | Useri;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articole_select".
 */
export interface ArticoleSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  limba?: T;
  versiuneAlternativa?: T;
  continutHashTradus?: T;
  necesitaRetraducere?: T;
  pilon?: T;
  subcategorie?: T;
  subcategorieEducatie?: T;
  tip?: T;
  excerpt?: T;
  continut?: T;
  imaginePrincipala?: T;
  galerie?:
    | T
    | {
        imagine?: T;
        caption?: T;
        credit?: T;
        id?: T;
      };
  videoTitlu?: T;
  videoUrl?: T;
  surse?: T;
  sursaNume?: T;
  sursaLink?: T;
  producator?: T;
  linkProducator?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  autorPrincipal?: T;
  coautori?: T;
  verificatorEditorial?: T;
  verificatorMedical?: T;
  contributoriExperti?: T;
  editorialStatus?: T;
  esteBreaking?: T;
  publishedAt?: T;
  significantUpdatedAt?: T;
  clusterHash?: T;
  unghi?: T;
  generatAutomat?: T;
  corectatCompliance?: T;
  numarConfirmari?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "autori_select".
 */
export interface AutoriSelect<T extends boolean = true> {
  profileType?: T;
  fullName?: T;
  slug?: T;
  publicTitle?: T;
  primaryAffiliation?: T;
  profileImage?: T;
  shortBio?: T;
  biography?: T;
  platformRoleDescription?: T;
  publicLocation?: T;
  displayOrder?: T;
  editorialRoles?: T;
  expertiseAreas?:
    | T
    | {
        name?: T;
        description?: T;
        verified?: T;
        order?: T;
        id?: T;
      };
  specialties?:
    | T
    | {
        label?: T;
        description?: T;
        order?: T;
        id?: T;
      };
  contributionTypes?: T;
  isMedicalReviewer?: T;
  medicalReviewScope?: T;
  credentials?:
    | T
    | {
        credentialType?: T;
        title?: T;
        institution?: T;
        country?: T;
        yearObtained?: T;
        yearExpires?: T;
        identifier?: T;
        verificationUrl?: T;
        publiclyVisible?: T;
        verified?: T;
        verifiedAt?: T;
        order?: T;
        id?: T;
      };
  professionalIdentifiers?:
    | T
    | {
        type?: T;
        value?: T;
        publiclyVisible?: T;
        verificationUrl?: T;
        verified?: T;
        id?: T;
      };
  verificationStatus?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  verificationSource?: T;
  nextVerificationDue?: T;
  verificationNotes?: T;
  documentsReviewed?: T;
  publicEmail?: T;
  website?: T;
  institutionalProfile?: T;
  orcidUrl?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        enabled?: T;
        order?: T;
        id?: T;
      };
  conflictOfInterestStatement?: T;
  affiliationsAndSponsorships?:
    | T
    | {
        organization?: T;
        relationshipType?: T;
        description?: T;
        startDate?: T;
        endDate?: T;
        currentlyActive?: T;
        publiclyVisible?: T;
        verified?: T;
        id?: T;
      };
  aiUseDisclosure?: T;
  publicationConsent?: T;
  consentConfirmedAt?: T;
  consentConfirmedBy?: T;
  consentScope?: T;
  profileImageConsent?: T;
  publicContactConsent?: T;
  consentWithdrawnAt?: T;
  consentNotes?: T;
  status?: T;
  publishedAt?: T;
  lastReviewedAt?: T;
  nextReviewDue?: T;
  inactiveAt?: T;
  archivedAt?: T;
  reviewedBy?: T;
  archivalReason?: T;
  linkedUser?: T;
  metaTitle?: T;
  metaDescription?: T;
  socialImage?: T;
  robots?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surse_select".
 */
export interface SurseSelect<T extends boolean = true> {
  nume?: T;
  url?: T;
  nivelIncredere?: T;
  tipCitarePermis?: T;
  permiteAutoGenerare?: T;
  pilon?: T;
  feedRSS?: T;
  regiune?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorii_select".
 */
export interface CategoriiSelect<T extends boolean = true> {
  nume?: T;
  slug?: T;
  pilon?: T;
  descriere?: T;
  necesitaDisclaimer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "useri_select".
 */
export interface UseriSelect<T extends boolean = true> {
  nume?: T;
  rol?: T;
  nivelAbonament?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  abonamentExpira?: T;
  limbaPreferata?: T;
  abonatNewsletter?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comentarii_select".
 */
export interface ComentariiSelect<T extends boolean = true> {
  continut?: T;
  autor?: T;
  articol?: T;
  status?: T;
  raspunsLa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tooluri_select".
 */
export interface TooluriSelect<T extends boolean = true> {
  nume?: T;
  slug?: T;
  descriere?: T;
  website?: T;
  linkAfiliat?: T;
  logo?: T;
  categorieTool?: T;
  scor?: T;
  pret?: T;
  recenzie?: T;
  studiuDeCaz?: T;
  verificatLa?: T;
  activ?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmaps_select".
 */
export interface RoadmapsSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  descriere?: T;
  nivel?: T;
  pasi?:
    | T
    | {
        titlu?: T;
        descriere?: T;
        resurse?:
          | T
          | {
              titlu?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cursuri_select".
 */
export interface CursuriSelect<T extends boolean = true> {
  titlu?: T;
  slug?: T;
  descriere?: T;
  imagine?: T;
  gratuit?: T;
  pretStripe?: T;
  lectii?:
    | T
    | {
        titlu?: T;
        continut?: T;
        videoURL?: T;
        durataMinute?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "callouri-ue_select".
 */
export interface CallouriUeSelect<T extends boolean = true> {
  titlu?: T;
  program?: T;
  descriere?: T;
  finantareMax?: T;
  deadline?: T;
  eligibilRomania?: T;
  pilonRelevant?: T;
  linkOficial?: T;
  activ?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  limba?: T;
  segment?: T;
  confirmat?: T;
  confirmationLastSentAt?: T;
  userAsociat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  hashMD5?: T;
  sursaImagine?: T;
  dreptUtilizareConfirmat?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  excerpt?: T;
  keywords?: T;
  url?: T;
  language?: T;
  editorialStatus?: T;
  articleType?: T;
  publishedAt?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  identity: {
    /**
     * Denumirea completă a platformei.
     */
    siteName: string;
    /**
     * Denumirea compactă utilizată în interfață.
     */
    shortName: string;
    /**
     * Mesajul scurt care descrie platforma.
     */
    tagline?: string | null;
    logoPrimary?: (number | null) | Media;
    logoAlternative?: (number | null) | Media;
    favicon?: (number | null) | Media;
  };
  navigation?: {
    primaryNavigation?:
      | {
          label: string;
          linkType: 'internal' | 'external';
          href: string;
          openInNewTab?: boolean | null;
          showInDesktop?: boolean | null;
          showInMobile?: boolean | null;
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
    headerActions?:
      | {
          label: string;
          actionType: 'link' | 'search' | 'languageSwitcher' | 'login';
          href?: string | null;
          style: 'link' | 'secondary' | 'primary';
          enabled?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  languageSettings: {
    availableLanguages: {
      code: 'ro' | 'en';
      label: string;
      shortLabel: string;
      enabled?: boolean | null;
      order: number;
      id?: string | null;
    }[];
    defaultLanguage: 'ro' | 'en';
    showLanguageSwitcher?: boolean | null;
  };
  trustBar?: {
    enabled?: boolean | null;
    items?:
      | {
          label: string;
          icon?: ('verified' | 'sources' | 'updated' | 'transparent' | 'independent' | 'medicalReview') | null;
          description?: string | null;
          enabled?: boolean | null;
          order: number;
          id?: string | null;
        }[]
      | null;
    /**
     * Textul linkului către pagina metodologiei.
     */
    methodologyLabel?: string | null;
    /**
     * Rută internă, de exemplu /ro/metodologie.
     */
    methodologyHref?: string | null;
  };
  methodology?: {
    enabled?: boolean | null;
    title?: string | null;
    summary?: string | null;
    pageLabel?: string | null;
    /**
     * Rută internă, de exemplu /ro/metodologie.
     */
    pageHref?: string | null;
    principles?:
      | {
          title: string;
          description: string;
          enabled?: boolean | null;
          order: number;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    emailLabel?: string | null;
    emailPlaceholder?: string | null;
    submitLabel?: string | null;
    consentText?: string | null;
    successMessage?: string | null;
    alreadySubscribedMessage?: string | null;
    invalidEmailMessage?: string | null;
    genericErrorMessage?: string | null;
    privacyLabel?: string | null;
    /**
     * Rută internă, de exemplu /ro/confidentialitate.
     */
    privacyHref?: string | null;
  };
  footer?: {
    footerEnabled?: boolean | null;
    footerIntro?: string | null;
    footerSections?:
      | {
          title: string;
          enabled?: boolean | null;
          order: number;
          links?:
            | {
                label: string;
                linkType: 'internal' | 'external';
                href: string;
                openInNewTab?: boolean | null;
                enabled?: boolean | null;
                order: number;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    copyrightText?: string | null;
  };
  contact?: {
    enabled?: boolean | null;
    contactTitle?: string | null;
    /**
     * Adresa afișată public pentru contact.
     */
    publicEmail?: string | null;
    phone?: string | null;
    address?: string | null;
    contactPageLabel?: string | null;
    /**
     * Rută internă, de exemplu /ro/contact.
     */
    contactPageHref?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'linkedin' | 'youtube' | 'instagram' | 'x' | 'tiktok' | 'github';
        label?: string | null;
        url: string;
        enabled?: boolean | null;
        order: number;
        id?: string | null;
      }[]
    | null;
  legalLinks: {
    label: string;
    href: string;
    enabled?: boolean | null;
    order: number;
    id?: string | null;
  }[];
  editorialDefaults?: {
    readMoreLabel?: string | null;
    latestArticlesLabel?: string | null;
    viewAllLabel?: string | null;
    updatedLabel?: string | null;
    verifiedLabel?: string | null;
    readingTimeLabel?: string | null;
    sourceLabel?: string | null;
    correctionsLabel?: string | null;
    sponsoredLabel?: string | null;
    aiDisclosureLabel?: string | null;
  };
  accessibility?: {
    skipToContentLabel?: string | null;
    openMenuLabel?: string | null;
    closeMenuLabel?: string | null;
    searchLabel?: string | null;
    languageSwitcherLabel?: string | null;
    externalLinkLabel?: string | null;
    previousPageLabel?: string | null;
    nextPageLabel?: string | null;
    loadingLabel?: string | null;
    errorLabel?: string | null;
  };
  metadata: {
    defaultMetaTitle?: string | null;
    defaultMetaDescription?: string | null;
    defaultShareImage?: (number | null) | Media;
    siteAuthor?: string | null;
    publisherName?: string | null;
    /**
     * Formatul implicit utilizat la distribuirea paginilor.
     */
    twitterCardType: 'summary' | 'summary_large_image';
    /**
     * Paginile private și tehnice vor suprascrie această setare în cod.
     */
    robotsDefault: 'indexFollow' | 'noindexNofollow';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  identity?:
    | T
    | {
        siteName?: T;
        shortName?: T;
        tagline?: T;
        logoPrimary?: T;
        logoAlternative?: T;
        favicon?: T;
      };
  navigation?:
    | T
    | {
        primaryNavigation?:
          | T
          | {
              label?: T;
              linkType?: T;
              href?: T;
              openInNewTab?: T;
              showInDesktop?: T;
              showInMobile?: T;
              enabled?: T;
              id?: T;
            };
        headerActions?:
          | T
          | {
              label?: T;
              actionType?: T;
              href?: T;
              style?: T;
              enabled?: T;
              id?: T;
            };
      };
  languageSettings?:
    | T
    | {
        availableLanguages?:
          | T
          | {
              code?: T;
              label?: T;
              shortLabel?: T;
              enabled?: T;
              order?: T;
              id?: T;
            };
        defaultLanguage?: T;
        showLanguageSwitcher?: T;
      };
  trustBar?:
    | T
    | {
        enabled?: T;
        items?:
          | T
          | {
              label?: T;
              icon?: T;
              description?: T;
              enabled?: T;
              order?: T;
              id?: T;
            };
        methodologyLabel?: T;
        methodologyHref?: T;
      };
  methodology?:
    | T
    | {
        enabled?: T;
        title?: T;
        summary?: T;
        pageLabel?: T;
        pageHref?: T;
        principles?:
          | T
          | {
              title?: T;
              description?: T;
              enabled?: T;
              order?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        emailLabel?: T;
        emailPlaceholder?: T;
        submitLabel?: T;
        consentText?: T;
        successMessage?: T;
        alreadySubscribedMessage?: T;
        invalidEmailMessage?: T;
        genericErrorMessage?: T;
        privacyLabel?: T;
        privacyHref?: T;
      };
  footer?:
    | T
    | {
        footerEnabled?: T;
        footerIntro?: T;
        footerSections?:
          | T
          | {
              title?: T;
              enabled?: T;
              order?: T;
              links?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    href?: T;
                    openInNewTab?: T;
                    enabled?: T;
                    order?: T;
                    id?: T;
                  };
              id?: T;
            };
        copyrightText?: T;
      };
  contact?:
    | T
    | {
        enabled?: T;
        contactTitle?: T;
        publicEmail?: T;
        phone?: T;
        address?: T;
        contactPageLabel?: T;
        contactPageHref?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        enabled?: T;
        order?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        enabled?: T;
        order?: T;
        id?: T;
      };
  editorialDefaults?:
    | T
    | {
        readMoreLabel?: T;
        latestArticlesLabel?: T;
        viewAllLabel?: T;
        updatedLabel?: T;
        verifiedLabel?: T;
        readingTimeLabel?: T;
        sourceLabel?: T;
        correctionsLabel?: T;
        sponsoredLabel?: T;
        aiDisclosureLabel?: T;
      };
  accessibility?:
    | T
    | {
        skipToContentLabel?: T;
        openMenuLabel?: T;
        closeMenuLabel?: T;
        searchLabel?: T;
        languageSwitcherLabel?: T;
        externalLinkLabel?: T;
        previousPageLabel?: T;
        nextPageLabel?: T;
        loadingLabel?: T;
        errorLabel?: T;
      };
  metadata?:
    | T
    | {
        defaultMetaTitle?: T;
        defaultMetaDescription?: T;
        defaultShareImage?: T;
        siteAuthor?: T;
        publisherName?: T;
        twitterCardType?: T;
        robotsDefault?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'articole';
      value: number | Articole;
    } | null;
    global?: string | null;
    user?: (number | null) | Useri;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}